version: '3.8'

services:
  sistema-pu:
    build: .
    ports:
      - "9993:9993"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PSW=${DB_PSW}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped